<a href="https://colab.research.google.com/github/jmamath/UVS-Probabilite-Statistiques/blob/master/Introduction_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Tutoriel 1. Python et Numpy

### Introduction

Ce didacticiel fournit une introduction pratique au langage de programmation Python et à la bibliothèque Numpy pour le calcul scientifique.

### Qu'attend-on de vous:
Ce tutoriel n'est pas à faire en une fois, mais plutôt fournit des notions clé en main pour manipuler des données avec Numpy et Python.
Utilisez-le à votre guise pour perfectionner votre Python, ou pour répondre à un problème spécifique.


## Introduction
Python est un excellent langage de programmation polyvalent, mais avec l'aide de quelques bibliothèques populaires (numpy, scipy, matplotlib), il devient un environnement puissant pour l'informatique scientifique.

Nous nous attendons à ce que beaucoup d’entre vous connaissent déjà Python et Numpy; pour le reste d'entre vous, cette section servira de cours accéléré à la fois sur le langage de programmation Python et sur l'utilisation de Python pour l'informatique scientifique.

Dans ce tutoriel, nous couvrirons:

* Basic Python: Types de données de base (Conteneurs, Listes, Dictionnaires, Ensembles, Tuples), Fonctions, Classes
* Numpy: Tableaux, Indexation de tableaux, Types de données, Calculs de tableaux, Radiodiffusion
* Matplotlib: Traçage, sous-parcelles, Images
* IPython: Création de cahiers, workflows typiques

## Notions de base de Python
Python est un langage de programmation multiparadigme de haut niveau à typage dynamique. On dit souvent que le code Python ressemble presque au pseudocode, car il vous permet d’exprimer des idées très puissantes avec très peu de lignes de code tout en étant très lisible. A titre d'exemple, voici une implémentation de l'algorithme classique quicksort en Python:

REMARQUE: dans Colab, vous pouvez exécuter le code dans une cellule en cliquant à l'intérieur de celle-ci et en appuyant simultanément sur les touches Maj + Entrée.

## Versions de python
Il existe actuellement deux versions différentes de Python, 2.7 et 3.4. De manière quelque peu déroutante, Python 3.0 a introduit de nombreuses modifications du langage incompatibles avec les versions antérieures, de sorte que le code écrit pour 2.7 peut ne pas fonctionner sous 3.4 et inversement. Pour cette classe, tout le code utilisera Python 2.7.

Vous pouvez vérifier votre version de Python sur la ligne de commande en exécutant python --version.

## Types de données de base
### Nombres
Les entiers et les flottants fonctionnent comme vous le voudriez des autres langues:

In [0]:
x = 3
print(x, type(x))

3 <class 'int'>


In [0]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;

4
2
6
9


In [0]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [0]:
y = 2.5
print(type(y)) # Prints "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Notez que contrairement à de nombreux langages, Python ne possède pas d'opérateurs unaires d'incrémentation (x ++) ou de décrémentation (x--).

Python a également des types intégrés pour les entiers longs et les nombres complexes; vous pouvez trouver tous les détails dans la documentation.

###Booléens
Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [0]:
t, f = True, False
print(type(t)) # Prints "<type 'bool'>"

<class 'bool'>


Regardons maintenant les opérations:

In [0]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


### Strings

In [0]:
hello = 'hello'   # apostrophe
world = "world"   # guillements
print(hello, len(hello))

hello 5


In [0]:
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

hello world


Les chaînes de charactères ont un tas de méthodes utiles; par exemple:

In [0]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


Vous pouvez trouver une liste de toutes les méthodes de chaîne dans la documentation.


### Les conteneurs
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

In [0]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1]) 

[3, 1, 2] 2
2


In [0]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [0]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

[3, 1, 'foo', 'bar']


In [0]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs) 

bar [3, 1, 'foo']


Comme d'habitude, vous trouverez tous les détails sanglants sur les listes dans la documentation.

### Slicing
En plus d'accéder aux éléments de liste un à la fois, Python fournit une syntaxe concise pour accéder aux sous-listes. c'est ce qu'on appelle le découpage en tranches:

In [0]:
nums = [1,2,3,4,5]    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 8, 4]"

[1, 2, 3, 4, 5]
[3, 4]
[3, 4, 5]
[1, 2]
[1, 2, 3, 4, 5]
[1, 2, 3, 4]
[1, 2, 8, 9, 5]


### Les boucles
Vous pouvez parcourir les éléments d'une liste comme ceci:

In [0]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


Si vous souhaitez accéder à l'index de chaque élément dans le corps d'une boucle, utilisez la fonction énumérée intégrée:

In [0]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


Lors de la programmation, nous souhaitons fréquemment transformer un type de données en un autre. Comme exemple simple, considérons le code suivant qui calcule les nombres carrés:

In [0]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


Vous pouvez simplifier ce code en utilisant une liste de compréhension:

In [0]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


On peut aussi introduire des conditions

In [0]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


### Dictionaires
Un dictionnaire stocke des paires (clé, valeur), similaires à une carte en Java ou à un objet en Javascript. Vous pouvez l'utiliser comme ceci:

In [0]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [0]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish']) 

wet


In [0]:
print(d['monkey'])  # Exemple d'erreur KeyError: 'monkey' not a key of d

KeyError: ignored

In [0]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

N/A
wet


In [0]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

N/A


Vous pouvez trouver tout ce que vous devez savoir sur les dictionnaires dans la documentation.

Il est facile de parcourir les clés d'un dictionnaire:

In [0]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Compréhensions de dictionnaire: elles ressemblent aux compréhensions de liste, mais vous permettent de construire facilement des dictionnaires. Par exemple:

In [0]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


### Ensembles
Un ensemble est une collection non ordonnée d'éléments distincts. Comme exemple simple, considérons ce qui suit:

In [0]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"

True
False


In [0]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # 

True
3


In [0]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))  

3
2


### Couples
Un couple est une liste de valeurs ordonnée (immuable) ils sont  à bien des égards similaire à une liste; L'une des différences les plus importantes est que les couples peuvent être utilisés comme clés dans les dictionnaires et comme éléments d'ensembles, alors que les listes ne le peuvent pas. Voici un exemple trivial:

In [0]:
d = {(x, x + 1): x for x in range(10)}  # Créer un dictionaire avec des couples en entrée
t = (5, 6)       # Crée un couple
print(type(t))
print(d[t])       
print(d[(1, 2)])

<class 'tuple'>
5
1


### Functions
Les fonctions Python sont définies à l'aide du mot clé def. Par exemple:

In [0]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


Nous allons souvent définir des fonctions pour prendre des arguments optionnels en  mots clés, comme ceci:

In [0]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s' % name.upper())  # Majuscule si loud est vrai
    else:
        print('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


### Classes
La syntaxe permettant de définir des classes en Python est simple:

In [0]:
class Greeter:

    # Constructeur
    def __init__(self, name):
        self.name = name  # Crée une variable instance

    # Méthethode d'instance
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construitune instance de la classe Greeter
g.greet()            # Appelle la méthode d'instance; "Hello, Fred"
g.greet(loud=True)   # Appelle la méthode d'instance avec un paramètre; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


#Numpy

Numpy est la bibliothèque de base du calcul scientifique en Python (voir la documentation complète disponible en ligne). Il fournit un objet tableau multidimensionnel hautes performances et des outils pour utiliser ces tableaux. Si vous connaissez déjà MATLAB, vous trouverez peut-être ce tutoriel utile pour commencer à utiliser Numpy.

Pour utiliser Numpy, nous devons d’abord importer le paquet numpy:

In [0]:
import numpy as np

###Tableaux

Un tableau numpy est une grille de valeurs, toutes du même type, indexées par un tuple d'entiers non négatifs. Le nombre de dimensions est le rang du tableau. la forme d'un tableau est un tuple d'entiers donnant la taille du tableau le long de chaque dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [0]:
a = np.array([1, 2, 3])  # Créer un tableau de rang 1
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Changer un élément du tableau
print(a)   

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [0]:
b = np.array([[1,2,3],[4,5,6]])   # Créer un tableau de rang 2
print (b)

[[1 2 3]
 [4 5 6]]


In [0]:
print (b.shape)                
print (b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy fournit également de nombreuses fonctions pour créer des tableaux:

In [0]:
a = np.zeros((2,2))  # Créer un tableau de tous les zéros
print (a)

[[0. 0.]
 [0. 0.]]


In [0]:
b = np.ones((1,2))   # Créer un tableau de tous ceux
print (b)

[[1. 1.]]


In [0]:
c = np.full((2,2), 7) # Créer un tableau constant
print (c) 

[[7 7]
 [7 7]]


In [0]:
d = np.eye(2)        # Créer une matrice d'identité 2x2
print (d)

[[1. 0.]
 [0. 1.]]


In [0]:
e = np.random.random((2,2)) # Créer un tableau rempli de valeurs aléatoires
print (e)

[[0.12817984 0.18750088]
 [0.05895338 0.78324432]]


### Indexation des tableaux

Numpy propose plusieurs méthodes pour indexer dans des tableaux.

Tranchage: similaires aux listes Python, les tableaux numpy peuvent être tranchés. Comme les tableaux peuvent être multidimensionnels, vous devez spécifier une tranche pour chaque dimension du tableau:

In [0]:
import numpy as np

# Créer le tableau de rang 2 suivant avec une forme (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Utilisez le découpage pour extraire le sous-réseau constitué des 2 premières lignes.
# et colonnes 1 et 2; b est le tableau de forme suivant (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

[[2 3]
 [6 7]]


Une tranche d'un tableau est une vue dans les mêmes données, sa modification modifiera donc le tableau d'origine.

In [0]:
print (a[0, 1])  
b[0, 0] = 77    # b [0, 0] est la même donnée qu'un [0, 1]
print (a[0, 1])

2
77


Vous pouvez également combiner l'indexation d'entiers avec l'indexation de tranches. Cependant, cela produira un tableau de rang inférieur à celui d'origine. Notez que ceci est assez différent de la façon dont MATLAB gère le découpage en matrice:

In [0]:
# Créer le tableau de rang 2 suivant avec une forme (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array. Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as the original array:

In [0]:
row_r1 = a[1, :]    # Rang 1 vue de la deuxième rangée de a  
row_r2 = a[1:2, :]  # Rang 2 vue de la deuxième rangée de a
row_r3 = a[[1], :]  # Rang 3 vue de la deuxième rangée de a
print (row_r1, row_r1.shape) 
print (row_r2, row_r2.shape)
print (row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [0]:
# Nous pouvons faire la même distinction en accédant aux colonnes d'un tableau:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Indexation de tableaux entiers: lorsque vous indexez dans des tableaux numpy à l'aide de la découpe, la vue de tableau résultante sera toujours un sous-tableau du tableau d'origine. En revanche, l'indexation de tableaux de nombres entiers vous permet de construire des tableaux arbitraires en utilisant les données d'un autre tableau. Voici un exemple:

In [0]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Un exemple d'indexation de tableau entier.
# Le tableau retourné aura la forme (3,) et 
print (a[[0, 1, 2], [0, 1, 0]])

# L'exemple ci-dessus d'indexation de tableau de nombres entiers est équivalent à ceci:
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [0]:
# Lorsque vous utilisez l'indexation de tableaux entiers, vous pouvez réutiliser le même
# élément du tableau source:
print (a[[0, 0], [1, 1]])

# Équivalent à l'exemple précédent d'indexation de tableau de nombres entiers
print (np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [0]:
# Créer un nouveau tableau à partir duquel nous allons sélectionner des éléments
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [0]:
# Créer un tableau d'indices
b = np.array([0, 2, 0, 1])

# Sélectionnez un élément de chaque ligne de a en utilisant les indices de b
print (a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [0]:
# Mutez un élément de chaque ligne de a en utilisant les indices de b
a[np.arange(4), b] += 10
print (a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Indexation de tableau booléen: L'indexation de tableau booléen vous permet de sélectionner des éléments arbitraires d'un tableau. Ce type d'indexation est fréquemment utilisé pour sélectionner les éléments d'un tableau qui remplissent certaines conditions. Voici un exemple:

In [0]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Trouvez les éléments de a qui sont plus grands que 2;
                    # cela retourne un tableau numpy de booléens de même
                    # forme comme un, où chaque emplacement de bool_idx dit
                    # si cet élément de a est> 2.
print (bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [0]:
# Nous utilisons l'indexation de tableau booléen pour construire un tableau de rang 1
# constitué des éléments d'un correspondant aux valeurs vraies
# de bool_idx
print (a[bool_idx])

# Nous pouvons faire tout ce qui précède dans une seule déclaration concise:
print (a[a > 2])

[3 4 5 6]
[3 4 5 6]


Par souci de brièveté, nous avons laissé de nombreux détails sur l'indexation de tableaux numpy; Si vous voulez en savoir plus, vous devriez lire la documentation.

###Types de données

Chaque tableau numpy est une grille d'éléments du même type. Numpy fournit un grand ensemble de types de données numériques que vous pouvez utiliser pour construire des tableaux. Numpy essaie de deviner un type de données lorsque vous créez un tableau, mais les fonctions qui construisent des tableaux incluent également un argument facultatif pour spécifier explicitement le type de données. Voici un exemple:

In [0]:
x = np.array([1, 2])  # Laisser numpy choisir le type de données
y = np.array([1.0, 2.0])  # Laisser numpy choisir le type de données
z = np.array([1, 2], dtype=np.int64)  # Forcer un type de données particulier

print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


Vous pouvez lire tout sur les types de données numpy dans la documentation.

### Mathématiques du tableau

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [0]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Somme élémentaire; les deux produisent le tableau
print (x + y)
print (np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [0]:
# Différence par élément; les deux produisent le tableau
print (x - y)
print (np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [0]:
# Produit par élément; les deux produisent le tableau
print (x * y)
print (np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [0]:
# Division élémentaire; les deux produisent le tableau
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [0]:
# Racine carrée par élément; produit le tableau
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Notez que contrairement à MATLAB, * est une multiplication élément par élément, pas une multiplication matricielle. Nous utilisons plutôt la fonction point pour calculer les produits internes des vecteurs, pour multiplier un vecteur par une matrice et pour multiplier des matrices. dot est disponible à la fois en tant que fonction dans le module numpy et en tant que méthode d'instance d'objets tableau:

In [0]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Produit intérieur des vecteurs; les deux produisent 219
print (v.dot(w))
print (np.dot(v, w))

219
219


In [0]:
# Produit matriciel / vectoriel; les deux produisent le tableau de rang 1 [29 67]
print (x.dot(v))
print (np.dot(x, v))

[29 67]
[29 67]


In [0]:
# Matrice / produit matriciel; les deux produisent le tableau de rang 2
# [[19 22]
#  [43 50]]
print (x.dot(y))
print (np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy fournit de nombreuses fonctions utiles pour effectuer des calculs sur des tableaux; l'un des plus utiles est la somme:

In [0]:
x = np.array([[1,2],[3,4]])

print (np.sum(x))  # Calculer la somme de tous les éléments; estampes "10"
print (np.sum(x, axis=0))  # Calculer la somme de chaque colonne; estampes "[4 6]"
print (np.sum(x, axis=1))  # Calculer la somme de chaque ligne; estampes "[3 7]"

10
[4 6]
[3 7]


Vous trouverez la liste complète des fonctions mathématiques fournies par numpy dans la documentation.
Outre le calcul de fonctions mathématiques à l'aide de tableaux, nous avons souvent besoin de remodeler ou de manipuler des données dans des tableaux. L’exemple le plus simple de ce type d’opération est la transposition d’une matrice; pour transposer une matrice, utilisez simplement l'attribut T d'un objet tableau:

In [0]:
print (x)
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [0]:
v = np.array([[1,2,3]])
print (v) 
print (v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


### Broadcasting

La diffusion est un mécanisme puissant qui permet à numpy de travailler avec des tableaux de formes différentes lorsqu’il effectue des opérations arithmétiques. Nous avons souvent un tableau plus petit et un tableau plus grand, et nous souhaitons utiliser le tableau plus petit plusieurs fois pour effectuer certaines opérations sur le tableau le plus grand.
Par exemple, supposons que nous voulions ajouter un vecteur constant à chaque ligne d'une matrice. Nous pourrions le faire comme ceci:

In [0]:
# Nous allons ajouter le vecteur v à chaque ligne de la matrice x,
# stocker le résultat dans la matrice y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Crée une matrice vide avec la même forme que x

# Ajouter le vecteur v à chaque ligne de la matrice x avec une boucle explicite
for i in range(4):
    y[i, :] = x[i, :] + v

print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Cela marche; Toutefois, lorsque la matrice x est très grande, le calcul d’une boucle explicite en Python peut être lent. Notez que l'ajout du vecteur v à chaque ligne de la matrice x revient à former une matrice vv en empilant plusieurs copies de v verticalement, puis en effectuant la somme élémentaire de x et vv. Nous pourrions implémenter cette approche comme ceci:

In [0]:
vv = np.tile(v, (4, 1))  # Empiler 4 copies de v les unes sur les autres
print (vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [0]:
y = x + vv  # Ajouter x et vv par élément
print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


La diffusion Numpy nous permet d'effectuer ce calcul sans créer réellement plusieurs copies de v. Considérez cette version, en utilisant la diffusion:

In [0]:
import numpy as np

# Nous allons ajouter le vecteur v à chaque ligne de la matrice x,
# stocker le résultat dans la matrice y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Ajouter v à chaque ligne de x en utilisant la diffusion
print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


La ligne y = x + v fonctionne même si x a une forme (4, 3) et v a une forme (3,) en raison de la diffusion; cette ligne fonctionne comme si v avait réellement une forme (4, 3), où chaque ligne était une copie de v, et la somme était effectuée élément par élément.

La diffusion simultanée de deux tableaux suit ces règles:



1.   Si les tableaux n'ont pas le même rang, préfixez la forme du tableau du rang inférieur avec des 1 jusqu'à ce que les deux formes aient la même longueur.
2.   Les deux tableaux sont dits compatibles dans une dimension s'ils ont la même taille ou si l'un des tableaux a la taille 1 dans cette dimension.
3.   Les tableaux peuvent être diffusés ensemble s'ils sont compatibles dans toutes les dimensions.
4.   Après la diffusion, chaque matrice se comporte comme si sa forme était égale au maximum, élément par élément, des formes des deux matrices en entrée.
5. Dans toute dimension où un tableau avait une taille de 1 et l'autre tableau avait une taille supérieure à 1, le premier tableau se comporte comme s'il avait été copié le long de cette dimension.

Si cette explication n’a pas de sens, essayez de la lire à partir de la documentation ou de cette explication.

Les fonctions qui prennent en charge la diffusion sont appelées fonctions universelles. Vous pouvez trouver la liste de toutes les fonctions universelles dans la documentation.

Voici quelques applications de la radiodiffusion:





In [0]:
# Calculer le produit extérieur des vecteurs
v = np.array([1,2,3])  # v a la forme (3,)
w = np.array([4,5])    # w a la forme (2,)
# Pour calculer un produit externe, nous transformons d'abord v en colonne
# vecteur de forme (3, 1); on peut alors le diffuser contre w pour céder
# une sortie de forme (3, 2), qui est le produit extérieur de v et w:

print (np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [0]:
# Ajouter un vecteur à chaque ligne d'une matrice
x = np.array([[1,2,3], [4,5,6]])
# x a la forme (2, 3) et v a la forme (3,) donc ils diffusent à (2, 3),
# donnant la matrice suivante:

print (x + v)

[[2 4 6]
 [5 7 9]]


In [0]:
# Ajouter un vecteur à chaque colonne d'une matrice
# x a la forme (2, 3) et w a la forme (2,).
# Si on transpose x alors il a la forme (3, 2) et peut être diffusé
# contre w pour donner un résultat de forme (3, 2); transposer ce résultat
# donne le résultat final de la forme (2, 3) qui est la matrice x avec
# le vecteur w ajouté à chaque colonne. Donne la matrice suivante:

print ((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [0]:
# Une autre solution consiste à transformer w en un vecteur ligne de forme (2, 1);
# on peut alors le diffuser directement contre x pour produire le même
# Sortiet.
print (x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [0]:
# Multipliez une matrice par une constante:
# x a la forme (2, 3). Numpy traite les scalaires comme des tableaux de formes ();
# ceux-ci peuvent être diffusés ensemble pour former (2, 3), produisant le
# tableau suivant:
print (x * 2)

[[ 2  4  6]
 [ 8 10 12]]


La diffusion rend généralement votre code plus concis et plus rapide. Vous devez donc vous efforcer de l'utiliser autant que possible.

Ce bref aperçu a abordé de nombreuses choses importantes que vous devez savoir sur numpy, mais est loin d’être complet. Consultez la référence numpy pour en savoir plus sur numpy.